services:
  postgresdb:
    image: postgres:17
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: postgress
      POSTGRES_DB: chaicode
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

volumes:
  postgres_data:
